name: marketplace
description: Desafio proposta para processo seletivo da i9XP.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_svg: ^0.15.0
  http: ^0.12.1
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1
  bloc_test: ^5.1.0
  carousel_slider: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo-alpha.png
    - assets/icons/icon-notification.png
    - assets/icons/icon-messages.png
    - assets/icons/icon-check.png
    - assets/images/button-next.png
    - assets/icons/icon-home.svg
    - assets/icons/icon-search.svg
    - assets/icons/icon-cart.svg
    - assets/icons/icon-profile.svg
    - assets/icons/icon-more.svg
    - assets/icons/icon-messages.svg
    - assets/images/item1.png
    - assets/images/item2.png
    - assets/images/item3.png

  fonts:
    - family: NeusaNextStd
      fonts:
        - asset: assets/fonts/NeusaNextStd-Light.otf
          weight: 300
        - asset: assets/fonts/NeusaNextStd-Regular.otf
          weight: 400
        - asset: assets/fonts/NeusaNextStd-Medium.otf
          weight: 500
        - asset: assets/fonts/NeusaNextStd-Bold.otf
          weight: 700
